version: '3.9'

services:
  micro-appoint-companies:
    depends_on:
      - mongodb
    build: .
    env_file:
      - .env
    image: micro-appoint-companies
    container_name: companies-backend
    networks:
      - companies-net
    ports:
      - 50051:50051
    volumes:
      - .:/app

  mongodb:
    image: mongo
    container_name: companies-db
    restart: always
    networks:
      - companies-net
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_ROOT_DATABASE=${DB_NAME}
    volumes:
      - db-data:/data/db
      - db-config:/data/configdb

volumes:
  db-data:
    driver: local
  db-config:
    driver: local

networks:
  companies-net:
    driver: bridge
