version: '3.9'

services:
  micro-appoint-gateway:
    build: .
    env_file:
      - .env
    image: micro-appoint-gateway
    container_name: gateway-backend
    networks:
      - micro-appoint-net
    ports:
      - 8080:8080
    volumes:
      - .:/app

networks:
  micro-appoint-net:
    name: micro-appoint-net 
    external: true
